import './globals.css'
import { Inter, Work_Sans } from 'next/font/google'

const inter = Work_Sans({
  subsets: ['latin'],
  display: "swap",
  weight: ["200", "400"]
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet='utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <meta http-equiv="X-UA-Compatible" content="ie=edge" /> */}
        <title>Tailwind Starter Template - Nordic Shop: Tailwind Toolbox</title>
        <meta name="description" content="Free open source Tailwind CSS Store template" />
        <meta name="keywords" content="tailwind,tailwindcss,tailwind css,css,starter template,free template,store template, shop layout, minimal, monochrome, minimalistic, theme, nordic" />

        <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
